---
default: '{"client_id":"675946843913-0ovt5tsbiga3mo1i6njv6ikarrp18s9l.apps.googleusercontent.com","access_token":"ya29.Ci8PA9E_Kq8YUE2ZCjkggBbsQJ5pdQvdVcOqDD5hZjmNGHCoLT5jSh2kQbLzi1eAyQ","refresh_token":"1/g9pkrggzC055F4-B93EQZMTWXZ2f4emYXwQUH9aQOtc","scope":["https://www.googleapis.com/auth/gmail.readonly"],"expiration_time_millis":1467122705000}'
